#!/usr/bin/env python3

# A python script to release all your stuck SLURM jobs from "requeue held"

import argparse
import subprocess
import os
import re


def get_args():
    parser = argparse.ArgumentParser(
        description="Release all SLURM held jobs for a user (yourself)."
    )
    parser.add_argument("user", help="Your username")
    parser.add_argument('--quiet', help='Do not produce output.', 
                        type=bool, default=False)

    return parser.parse_args()


def request_job_ids(username):
    cmd =  ["squeue", "--user", username, "-o", '"%.18i"']
    cmd = ' '.join(cmd)
    return os.popen(cmd).read()


def extract_job_ids(job_ids):
    # Pull out all job ids as a list
    return re.findall(r"[\d_-]+", job_ids)


def release_all_jobs(job_ids, quite=False):
    # Use scontrol to release user's jobs
    for each_id in job_ids:
        if not quite:
            print("Releasing job", each_id)
        subprocess.run(["scontrol", "release", str(each_id)])
    if not quite:
        print(f'Released {len(job_ids)} jobs')
    


def main():
    args = get_args()
    job_id_text = request_job_ids(args.user)
    job_ids = extract_job_ids(job_id_text)
    release_all_jobs(job_ids, quite=args.quiet)


if __name__ == "__main__":
    main()


